# .yml - 提供了结构化及其嵌套的格式
# properties server.port = 8081
# server.tomcat.url-encoding=utf-8
# 如果你的配置文件放在 resource文件中 springboot会自动进行读取
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
#数据源与jpa的配置
spring:
  datasource:
   url: jdbc:mysql://localhost/mansocks?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: 123456
 #redis
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:com.mansocks.dao.Mapper/* #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.mansocks.dao  # 注意：对应dao接口的路径



