server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
   url: jdbc:mysql://192.168.51.213/mansocks?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: 123456

   type: com.alibaba.druid.pool.DruidDataSource
   filters: stat , wall , log4j
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
  redis:
    host: 192.168.51.213
    port: 6379
mybatis:
  mapper-locations: classpath:com.mansocks.dao.Mapper/*
  type-aliases-package: com.mansocks.dao



